version: '3'

services:
  database:
    image: postgres:${POSTGRES_VERSION}-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - '5432:5432' # host:container
    volumes:
      - initdb:/docker-entrypoint-initdb.d
      - datadb:/var/lib/postgresql/data:rw

volumes:
  initdb: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'docker/database/initdb'
  datadb: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'docker/database/datadb'