version: '3'

services:
  database:
    image: postgres:${POSTGRES_VERSION}-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports: 
      - ${POSTGRES_PUBLIC_PORT}:5432 # host:container
    volumes:
      - init-db:/docker-entrypoint-initdb.d
      - data-db:/var/lib/postgresql/data:rw
    networks:
      - back

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: database_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 80 
    volumes:
      - data-pgadmin:/var/lib/pgadmin
    ports: 
      - ${PGADMIN_PUBLIC_PORT}:80 # host:container
    networks:
      - back

  rabbitmq:
    image: rabbitmq:3.8-management
    restart: always
    container_name: rabbitmq
    ports: 
      - 5672:5672
      - 15672:15672
    networks:
      - back

volumes:
  init-db: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'docker/database/init-db'
  data-db: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'docker/database/data-db' # Carefull, if you ubate this location, you mus update the script "docker-up-dev"
  data-pgadmin: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'docker/pgadmin/data-pgadmin'

networks: 
    back: